### PR TITLE
Helm improvements and publishing

### PR DESCRIPTION
**Pull request by Supporterino**
Hey there,

after some quick chatting in matrix, I took a quick look over the jellyfin helm chart and made some improvements to the workflows and releasing of the chart. The following things have changed:

- Don't rely on `yg` for chart releasing
- Split Chart Version and appVersion for async changes on both projects
- Generate helm docs from a template and the `values.yaml`
- Added a global readme with some basic instructions
- Add a PR job which automatically generates a new README for the chart

Some things can't be worked out in a fork so here is a list of TODOs before/while merging this PR.

- [ ] Create empty `gh-pages` branch
- [ ] Enable GH Pages on the previous mentioned branch
- [ ] Delete all old tags and releases
- [ ] Create the correct trigger in the docker build process to trigger the `app_release.yaml` to automatically update the chart
- [ ] (optional) Host the `index.yaml` at an additional location for better repo URL
- [ ] Update the README files with the correct repo URL

Caveats of the current release process is that if you want to create a standalone release you have to create a tag with the command line and push it since the GitHub Release gets created by chart releaser and can't be present during the action run.

### CODE REVIEW

**Review by crobibero — COMMENTED** [review]
If I'm reading this correctly, on Jellyfin version release all we would need to do is trigger the `Bump Helm Chart Version` workflow?

**Comment by Supporterino** [comment]
@crobibero yes that is the plan that once you release the docker container a new chart version is fully released. 

I will check the pipeline error later. Had no chance to really test in the fork

**Comment by Supporterino** [comment]
@crobibero The PR workflow should work now

**Comment by crobibero** [comment]
@Supporterino ci still failed

**Comment by Supporterino** [comment]
@crobibero  Alright had to move the documentation step to push on master to avoid issues with permissions when a PR comes from a forked repository but should work either way. Since only PR should trigger commit on master and version updates don't need documentation updates.

**Review by crobibero — APPROVED** [review]

**Comment by Supporterino** [comment]
@crobibero The additional steps in the PR description still need to be done. Otherwise the actions will run into erorrs. If you are looking for someone to maintain this repo I would be open to help

**Comment by Supporterino** [comment]
@crobibero yes it should be empty but present. The chart releaser will push to it. 
Have you implemented the trigger on the docker build side ? If not you could also trigger the Bump workflow now with the new jellyfin version.
If the old releases and tags are removed

**Comment by Supporterino** [comment]
@crobibero just saw that. Give me a moment I will open a PR with the fix

**Comment by Supporterino** [comment]
@crobibero https://github.com/jellyfin/jellyfin-helm/pull/22 should fix it

**Comment by crobibero** [comment]
@Supporterino Got further 😄 
https://github.com/jellyfin/jellyfin-helm/actions/runs/10774194377/job/29875676149

**Comment by Supporterino** [comment]
@crobibero My bad missed one path :) https://github.com/jellyfin/jellyfin-helm/pull/23 fixes it

**Comment by Supporterino** [comment]
@crobibero found another bug which needs a new token to push changes otherwise the release pipeline is not triggered. Check https://github.com/jellyfin/jellyfin-helm/pull/24 A Org PAT with push access should work

**Pull request merged**
